# PowerShell script to update missing Exchange attributes for a list of exported users
# CSV can be generated by querying AD for an incorrect or null targetAddress attribute on user objects
# Run in the on-premise Exchange Management Shell for the time being...
# Version 1.0 - Copyright DM Tech 2019

#Requires -Modules ActiveDirectory

$UsersList = (Import-Csv -Path "D:\Scripts\Input\UserTargetAddressIncorrect.csv")
$PrimaryDomain = "yourupndomain.com.au"
$TargetDomain = "YourTenancy.mail.onmicrosoft.com"
$UPNs = ($UsersList.UserPrincipalName).Trim()

Write-Host -ForegroundColor 'White' "`nImporting the following users:`n"
Write-Output $UPNs
Write-Host -ForegroundColor 'Green' "`n`nTotal users: " $UPNs.Count "`n"

foreach ($UPN in $UPNs) {

    $UserAccount = (Get-ADUser -Filter {UserPrincipalName -eq $UPN} -Properties * | Select-Object Name,SamAccountName,UserPrincipalName,ProxyAddresses,TargetAddress)
    Write-Host -ForegroundColor 'White' "`nUser account match:" $UserAccount.Name
    $UserSAM = $UserAccount.SamAccountName
    Write-Host -ForegroundColor 'White' "User SAM match:" $UserSAM
    $ProxyAddresses = $UserAccount.ProxyAddresses
    Write-Host -ForegroundColor 'White' "Proxy addresses:" 
    Write-Output $ProxyAddresses
    $Target = $UPN -replace $PrimaryDomain,$TargetDomain
    Write-Host -ForegroundColor 'White' "Setting target address:" $Target
    #$Alias = $UPN -replace '(@[A-Za-z.]+)',''
    #Set-ADUser -Identity $UserSAM -Replace @{ msExchRecipientDisplayType="-2147483642";msExchRecipientTypeDetails="2147483648";msExchRemoteRecipientType="4";targetAddress="$Target" }

    if ($null -eq $UserAccount.targetAddress) {
        Enable-RemoteMailbox $UPN -RemoteRoutingAddress $Target
    } else {
        Set-RemoteMailbox $UPN -RemoteRoutingAddress $Target -EmailAddressPolicyEnabled $True
    }

    Start-Sleep 1
}