# Connect to Azure AD
# Uses the cred file in $KeyPath generated by Functions-PSStoredCredentials.ps1
# Create an Environment Variable for the AdminUPN in your PS profile

$UserCredential = (Get-StoredCredential -UserName $Env:AdminUPN)

# Connecto to Azure and Msol
Connect-AzureAD -Credential $UserCredential # Will be the new way going forward
#Connect-MsolService -Credential $UserCredential # For compatibility 