# Connect to Exchange Online, optionally the Security & Compliance Center
# Uses the cred file in $KeyPath generated by Functions-PSStoredCredentials.ps1
# Create an Environment Variable for the AdminUPN in your PS profile

$UserCredential = (Get-StoredCredential -UserName $Env:AdminUPN)

# Connect to Exchange Online
$ExchSession = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://outlook.office365.com/powershell-liveid/ -Credential $UserCredential -Authentication "Basic" -AllowRedirection
Import-PSSession $ExchSession -DisableNameChecking

# Connect to Security & Compliance Center
#$SccSession = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://ps.compliance.protection.outlook.com/powershell-liveid/ -Credential $UserCredential -Authentication "Basic" -AllowRedirection
#Import-PSSession $SccSession -Prefix SCC