# Connect to Office 365 Exchange Online the fast way
# Uses the cred file in $KeyPath generated by Functions-PSStoredCredentials.ps1
# Create an Environment Variable for the AdminUPN in your PS profile

$UserCredential = (Get-StoredCredential -UserName $Env:AdminUPN)
$ProxyOptions = New-PSSessionOption -ProxyAccessType IEConfig
$Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://outlook.office365.com/powershell-liveid/ -Credential $UserCredential -Authentication Basic -AllowRedirection -SessionOption $ProxyOptions
Import-PSSession $Session -DisableNameChecking
